// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoaghmtibhrnknjxxpfq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvYWdobXRpYmhybmtuanh4cGZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc1NTY2NjEsImV4cCI6MjA1MzEzMjY2MX0.rbzTZR1W5xeQXSB2sTjDYltJpGWHaIyVzWd95HH_nGY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);